relation:
    items:
        - name: red
          color: "#ff0000"
        - name: green
          color: "#00ff00"
        - name: black
          color: "#000000"
    default:
        index: 1
        name: dummy
        color: "#FFFFFF"
switch:
    test: true
    grid: true
    straight-lines: true
    connector-auto-alignment: true
    node-rename: false
    live-redraw: false
subset:
    items:
        - name: train
          pattern: solid
        - name: test
          pattern: dashed
        - name: valid
          pattern: dashed-dotted
    patterns:
        - solid
        - dashed
        - dotted
        - dashed-dotted
    default:
        index: 0
        name: dummy
        pattern: solid
graph:
    bg-color: "#F5F5F5FF"
    grid-color: white
node:
    size: 100
connector:
    size: 20
    min: 10
    max: 100
    step: 10
