relation:
    items:
        - name: red
          color: "#ff0000"
        - name: green
          color: "#00ff00"
        - name: black
          color: "#000000"
    default:
        index: 1
        name: dummy
        color: "#FFFFFF"
switch:
    test: true
    grid: true
    straight-lines: true
    connector-auto-alignment: true
    node-rename: false
    live-redraw: false
graph:
    bg-color: "#F5F5F5FF"
    grid-color: white
node:
    size: 100
