relations:
    - name: red
      color: "#ff0000"
    - name: green
      color: "#00ff00"
    - name: black
      color: "#000000"
graph:
    bg-color: "#F5F5F5FF"
    grid-color: white
node:
    size: 100
